import { Inject, Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { eq, and, isNull } from 'drizzle-orm';
import { DATABASE_CONNECTION, DrizzleDb } from '../../db/connection';
import { sysUsers } from '../../db/schema/users';
import { sysDepartments } from '../../db/schema/sys-departments';
import { sysUserRoles } from '../../db/schema/user-roles';
import { sysRoles } from '../../db/schema/roles';

/**
 * Pushes user/department changes from NestJS (source of truth) into BPM, so
 * BPM's AssigneeResolver (which reads BPM's own users/departments) can resolve
 * approvers for codegen-table approvals.
 *
 * - NestJS is the source of truth; BPM is a mirrored backing store.
 * - Department BPM id = NestJS department `code`. User BPM id (EMPxxx) is
 *   generated by BPM on first sync and stored back on sys_users.bpm_user_id.
 * - Every method is failure-tolerant: it logs and swallows errors so a BPM
 *   outage never blocks the primary NestJS CRUD operation. A one-time backfill
 *   script catches anything missed.
 * - BPM requires every user to have a dept (NOT NULL); users without a dept are
 *   skipped until one is assigned.
 */
@Injectable()
export class BpmOrgSyncService {
  private readonly logger = new Logger(BpmOrgSyncService.name);
  private readonly bpmUrl: string;
  private readonly syncUserId: string;

  constructor(
    @Inject(DATABASE_CONNECTION) private readonly db: DrizzleDb,
    private readonly config: ConfigService,
  ) {
    this.bpmUrl = (this.config.get<string>('BPM_SERVICE_URL') || 'http://localhost:8090').replace(/\/$/, '');
    this.syncUserId = this.config.get<string>('BPM_SYNC_USER_ID') || 'EMP008';
  }

  // ===================== Users =====================

  async syncUser(userId: string): Promise<void> {
    try {
      const u = await this.db.select().from(sysUsers).where(eq(sysUsers.id, userId)).limit(1);
      if (u.length === 0) return;
      const user = u[0]!;

      if (!user.deptId) {
        this.logger.log(`syncUser ${userId}: no department assigned, skipping`);
        return;
      }
      const d = await this.db.select().from(sysDepartments).where(eq(sysDepartments.id, user.deptId)).limit(1);
      if (d.length === 0) {
        this.logger.warn(`syncUser ${userId}: department ${user.deptId} not found, skipping`);
        return;
      }
      const dept = d[0]!;
      // BPM "title" is cosmetic — derive it from the user's role names.
      const roleRows = await this.db
        .select({ name: sysRoles.name })
        .from(sysUserRoles)
        .innerJoin(sysRoles, eq(sysRoles.id, sysUserRoles.roleId))
        .where(and(eq(sysUserRoles.userId, userId), isNull(sysRoles.deletedAt)));
      const title = roleRows.map((r) => r.name).join('/');
      const payload = {
        name: user.nickname || user.username,
        deptId: dept.code,
        email: user.email ?? '',
        title,
      };

      if (user.bpmUserId) {
        await this.call('PUT', `users/${user.bpmUserId}`, payload);
        this.logger.log(`syncUser ${userId}: updated BPM user ${user.bpmUserId}`);
      } else {
        const res = await this.call('POST', 'users', payload);
        const empId: string | undefined = res?.data?.id;
        if (empId) {
          await this.db.update(sysUsers).set({ bpmUserId: empId }).where(eq(sysUsers.id, userId));
          this.logger.log(`syncUser ${userId}: created BPM user ${empId}`);
        }
      }
    } catch (e) {
      this.logger.warn(`syncUser ${userId} failed: ${(e as Error).message}`);
    }
  }

  async deleteUser(bpmUserId: string | null): Promise<void> {
    if (!bpmUserId) return;
    try {
      await this.call('DELETE', `users/${bpmUserId}`);
      this.logger.log(`deleteUser BPM ${bpmUserId}`);
    } catch (e) {
      this.logger.warn(`deleteUser ${bpmUserId} failed: ${(e as Error).message}`);
    }
  }

  // ===================== Departments =====================

  async syncDept(deptId: string): Promise<void> {
    try {
      const rows = await this.db.select().from(sysDepartments).where(eq(sysDepartments.id, deptId)).limit(1);
      if (rows.length === 0) return;
      const dept = rows[0]!;

      let parentCode: string | null = null;
      if (dept.parentId) {
        const p = await this.db.select().from(sysDepartments).where(eq(sysDepartments.id, dept.parentId)).limit(1);
        parentCode = p[0]?.code ?? null;
      }
      let leadBpmId: string | null = null;
      if (dept.leadId) {
        const l = await this.db
          .select({ bpmUserId: sysUsers.bpmUserId })
          .from(sysUsers)
          .where(eq(sysUsers.id, dept.leadId))
          .limit(1);
        leadBpmId = l[0]?.bpmUserId ?? null;
      }

      await this.call('POST', 'departments', {
        id: dept.code,
        name: dept.name,
        parentId: parentCode,
        leadId: leadBpmId,
      });
      this.logger.log(`syncDept ${dept.code}`);
    } catch (e) {
      this.logger.warn(`syncDept ${deptId} failed: ${(e as Error).message}`);
    }
  }

  async deleteDept(code: string | null): Promise<void> {
    if (!code) return;
    try {
      await this.call('DELETE', `departments/${code}`);
      this.logger.log(`deleteDept ${code}`);
    } catch (e) {
      this.logger.warn(`deleteDept ${code} failed: ${(e as Error).message}`);
    }
  }

  // ===================== HTTP =====================

  private async call(method: string, path: string, body?: unknown): Promise<any> {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), 5000);
    try {
      const res = await fetch(`${this.bpmUrl}/bpm/api/admin/${path}`, {
        method,
        headers: { 'Content-Type': 'application/json', 'x-user-id': this.syncUserId },
        body: body ? JSON.stringify(body) : undefined,
        signal: ctrl.signal,
      });
      const text = await res.text();
      let json: any = null;
      try { json = JSON.parse(text); } catch { /* non-JSON response */ }
      if (!res.ok) {
        throw new Error(`${method} ${path} -> ${res.status} ${text.slice(0, 120)}`);
      }
      return json;
    } finally {
      clearTimeout(timer);
    }
  }
}
