// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from '/home/cat/gin-vue-admin/apps/web/src/.umi/plugin-access';
export { Provider, useModel } from '/home/cat/gin-vue-admin/apps/web/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/home/cat/gin-vue-admin/apps/web/src/.umi/plugin-request';
// plugins types.d.ts
export * from '/home/cat/gin-vue-admin/apps/web/src/.umi/plugin-access/types.d';
export * from '/home/cat/gin-vue-admin/apps/web/src/.umi/plugin-antd/types.d';
export * from '/home/cat/gin-vue-admin/apps/web/src/.umi/plugin-layout/types.d';
export * from '/home/cat/gin-vue-admin/apps/web/src/.umi/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/home/cat/gin-vue-admin/node_modules/.pnpm/@umijs+renderer-react@4.6.59_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from '/home/cat/gin-vue-admin/node_modules/.pnpm/@umijs+renderer-react@4.6.59_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/home/cat/gin-vue-admin/node_modules/.pnpm/umi@4.6.59_@babel+core@7.23.6_@types+node@25.9.1_@types+react@19.2.16_eslint@8.35.0_jest@30.4_csztgkbi7wbv64ezlmqtryufde/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
