// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import SettingOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/SettingOutlined';
import TeamOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import SafetyCertificateOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/SafetyCertificateOutlined';
import MenuOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/MenuOutlined';
import ApiOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/ApiOutlined';
import SlidersOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/SlidersOutlined';
import BookOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/BookOutlined';
import StopOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/StopOutlined';
import ControlOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/ControlOutlined';
import ThunderboltOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/ThunderboltOutlined';
import ToolOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/ToolOutlined';
import FileOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/FileOutlined';
import CodeOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/CodeOutlined';
import HistoryOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/HistoryOutlined';
import AppstoreOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
import ExportOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/ExportOutlined';
import BranchesOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/BranchesOutlined';
import BlockOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/BlockOutlined';
import KeyOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/KeyOutlined';
import MonitorOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/MonitorOutlined';
import AuditOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/AuditOutlined';
import SecurityScanOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/SecurityScanOutlined';
import WarningOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/WarningOutlined';
import IdcardOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/IdcardOutlined';
import InfoCircleOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/InfoCircleOutlined';
import TableOutlined from '/home/cat/gin-vue-admin/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { DashboardOutlined, SettingOutlined, TeamOutlined, SafetyCertificateOutlined, MenuOutlined, ApiOutlined, SlidersOutlined, BookOutlined, StopOutlined, ControlOutlined, ThunderboltOutlined, ToolOutlined, FileOutlined, CodeOutlined, HistoryOutlined, AppstoreOutlined, ExportOutlined, BranchesOutlined, BlockOutlined, KeyOutlined, MonitorOutlined, AuditOutlined, SecurityScanOutlined, WarningOutlined, IdcardOutlined, InfoCircleOutlined, TableOutlined };
