package com.example.bpm.controller;

import com.example.bpm.auth.AuthInterceptor;
import com.example.bpm.auth.Result;
import com.example.bpm.service.OrgService;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import java.util.HashMap;
import java.util.Map;

/**
 * Organization sync endpoints — called by the NestJS low-code platform to mirror
 * users and departments into BPM (BPM is the system-of-record for the Flowable
 * approval org model: AssigneeResolver reads BPM's own users/departments).
 *
 * Auth: x-user-id header resolved by AuthInterceptor must carry the
 * {@code user:manage} permission (service account, e.g. the admin EMP id).
 * Network isolation is the trust boundary (BPM is not exposed to browsers).
 *
 * User id (EMPxxx) is generated by BPM on create and returned, so NestJS can
 * store it on sys_users.bpm_user_id. Department id is provided by the caller
 * (the NestJS department code).
 */
@RestController
@RequestMapping("/api/admin")
public class OrgSyncController {

    private final OrgService orgService;

    public OrgSyncController(OrgService orgService) {
        this.orgService = orgService;
    }

    // ===================== Users =====================

    /** Create a BPM user. Body: { name, deptId, email?, title? }. Returns the generated EMP id. */
    @PostMapping("/users")
    public Result<?> createUser(@RequestBody Map<String, Object> body, HttpServletRequest request) {
        AuthInterceptor.requirePermission(request, "user:manage");
        String name = str(body, "name");
        String deptId = str(body, "deptId");
        if (isBlank(name)) return Result.fail(400, "name is required");
        if (isBlank(deptId)) return Result.fail(400, "deptId is required");
        if (!orgService.deptExists(deptId)) return Result.fail(400, "department not found: " + deptId);
        String email = str(body, "email");
        String title = str(body, "title");
        String id = orgService.createUser(name, deptId, email, title);
        Map<String, Object> data = new HashMap<>();
        data.put("id", id);
        data.put("name", name);
        data.put("deptId", deptId);
        data.put("email", email == null ? "" : email);
        data.put("title", title == null ? "" : title);
        return Result.ok(data);
    }

    /** Full-state replace. Body: { name, deptId, email?, title? }. */
    @PutMapping("/users/{id}")
    public Result<?> updateUser(@PathVariable String id, @RequestBody Map<String, Object> body, HttpServletRequest request) {
        AuthInterceptor.requirePermission(request, "user:manage");
        String deptId = str(body, "deptId");
        if (deptId != null && !orgService.deptExists(deptId)) {
            return Result.fail(400, "department not found: " + deptId);
        }
        orgService.updateUser(id, str(body, "name"), deptId, str(body, "email"), str(body, "title"));
        return Result.ok(Map.of("id", id));
    }

    @DeleteMapping("/users/{id}")
    public Result<?> deleteUser(@PathVariable String id, HttpServletRequest request) {
        AuthInterceptor.requirePermission(request, "user:manage");
        orgService.deleteUser(id);
        return Result.ok(Map.of("id", id, "deleted", true));
    }

    // ===================== Departments =====================

    /** Create a BPM department. Body: { id (=NestJS code), name, parentId?, leadId? }. */
    @PostMapping("/departments")
    public Result<?> createDept(@RequestBody Map<String, Object> body, HttpServletRequest request) {
        AuthInterceptor.requirePermission(request, "user:manage");
        String id = str(body, "id");
        String name = str(body, "name");
        if (isBlank(id)) return Result.fail(400, "id is required");
        if (isBlank(name)) return Result.fail(400, "name is required");
        orgService.createDept(id, name, str(body, "parentId"), str(body, "leadId"));
        return Result.ok(Map.of("id", id));
    }

    @PutMapping("/departments/{id}")
    public Result<?> updateDept(@PathVariable String id, @RequestBody Map<String, Object> body, HttpServletRequest request) {
        AuthInterceptor.requirePermission(request, "user:manage");
        orgService.updateDept(id, str(body, "name"), str(body, "parentId"), str(body, "leadId"));
        return Result.ok(Map.of("id", id));
    }

    @DeleteMapping("/departments/{id}")
    public Result<?> deleteDept(@PathVariable String id, HttpServletRequest request) {
        AuthInterceptor.requirePermission(request, "user:manage");
        orgService.deleteDept(id);
        return Result.ok(Map.of("id", id, "deleted", true));
    }

    private static String str(Map<String, Object> body, String key) {
        Object v = body.get(key);
        return v == null ? null : v.toString();
    }

    private static boolean isBlank(String s) {
        return s == null || s.isBlank();
    }
}
